[book]
title = "Shell-Cell Documentation"
authors = ["Shell-Cell Contributors"]
language = "en"
src = "docs"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
