//! Crate metadata and build information
//!
//! This module provides access to build-time information such as crate name,
//! version, description, and repository URL.

/// Build-time information generated by the `built` crate
#[allow(clippy::doc_markdown)]
mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Returns the crate name
#[must_use]
pub fn name() -> &'static str {
    built_info::PKG_NAME
}

/// Returns the current crate version
#[must_use]
pub fn version() -> &'static str {
    built_info::PKG_VERSION
}

/// Returns the crate description
#[must_use]
pub fn description() -> &'static str {
    built_info::PKG_DESCRIPTION
}

/// Returns the repository URL
///
/// The `.git` suffix is stripped if present for cleaner URLs.
#[must_use]
pub fn repository() -> &'static str {
    built_info::PKG_REPOSITORY
        .strip_suffix(".git")
        .unwrap_or(built_info::PKG_REPOSITORY)
}
