name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-deny
        version: "0.19.0"
    - name: Run fmt
      run: cargo +nightly fmt --check
    - name: Clippy
      run: cargo clippy --all-targets
    - name: Run unit tests
      run: cargo test --bins
    - name: Deny
      run: cargo deny check
